spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wzy?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    ##    password: 123456
    database: 1
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000



mybatis-plus:
  configuration:
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-field: flag
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        ConnectTimeout: 30000
        ReadTimeout: 30000

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少64位的Base64对该令牌进行编码
  base64-secret: nx6Jj7ZHsDbHbyFX9vYGbL2BNsNblEo+9UER2/ABYwYVBRs3pJI6hfPR9sG867wpeO/2rXmRtZbyR4hMA12W0w==
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: "online-token:"
  # 验证码
  code-key: "captcha-code:"
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000


# 登录相关配置
login:
  #  是否限制单用户登录
  single-login: false
  # Redis用户登录缓存配置
  user-cache:
    # 存活时间/秒
    idle-time: 21600
  #  验证码
  login-code:
    #  验证码类型配置 查看 LoginProperties 类
    code-type: arithmetic
    #  登录图形验证码有效时间/分钟
    expiration: 2
    #  验证码高度
    width: 111
    #  验证码宽度
    height: 36
    # 内容长度
    length: 2
    # 字体名称，为空则使用默认字体
    font-name:
    # 字体大小
    font-size: 25

rsa:
  private_key: MIICeQIBADANBgkqhkiG9w0BAQEFAASCAmMwggJfAgEAAoGBAN05ILK43h2MFkKr43AL6kkh8OGWsJXXX6MCFelA7pMttEXdnc41b0BetL3Gu0CMXp+HWcs+muPQIIuRyDQISf6xQcNsyBJg7VYZC3lgy19dKSB8USM+5bhjRPCWehrbyLxw2530XQdIbiB3nm0r5Bw0gCXl1s2oUXkPeUGSak5hAgMBAAECgYEAtxplugfRsFsWwbBL253BGS8ClXWISz2sZtt/D0UzMpaNs5Yu21LW9kxtBPbMXizQ1PHOnK8AvLazeVH8hzSlKKNhqTdiQa6F3MDICQRJOqS36K1ulULBjauouhG09l3gn69V5mJNdkpRdLw0e7rDV4xAKvUWz/yd8l1zM6ACYwECQQD5l2h+8CKVkAebpUwN/ulQOWe6eN1+sHnQsfE/xSMzMhnmw0AaePj/LzeGf1eHw63cdW4WMxa5hFBBZ5uj0ak5AkEA4udAcFQSOTwRAv4daHWqrBnP85dIZ/+N6N8fdP3CZClh69++j3nPPFp+okhVIVi7cTUGzuUaCxIuUfDfGOkWaQJBANWg8IHly9Qz6S8hdk1saAqQd+Y1WW/8YOdtxs4MUCqbsWvApveBn63bnizyhdrgc8mEgWti4wp64653ndHDvJECQQC2kPDFMK/VA2KAsOwCj6J6hO5QBapJm1KYS2apIEBXjQBv5AAUuyKmYf3AH0j34sg2pz7KG4Zf4AoK/i7TgT/5AkEAnf3Kcm8vLZA1V/XER3Ou2jMKot4A/+P+/DBLM8kHKnj97TCmOMIc67mCfdDGMB35JxA5+Tp1jxLhlSVmQ2X0PQ==